apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [agent]
      interval = "30s"
      flush_interval = "10s"

    [[inputs.http_response]]
      urls = ["https://example.com"]
      response_status_code = 200
      response_timeout = "5s"

    [[inputs.ping]]
      urls = ["example.com"]
      method = "native"
      deadline = "10s"
  output.conf: |
    [[outputs.opentelemetry]]
      service_address = "https://ingress.${CORALOGIX_DOMAIN:-eu2.coralogix.com}:443/v1/metrics"
      timeout = "5s"

      [outputs.opentelemetry.coralogix]
        private_key = "${CORALOGIX_PRIVATE_KEY:-dummy}"
        application = "${CORALOGIX_APPLICATION:-telegrafix}"
        subsystem = "${CORALOGIX_SUBSYSTEM:-synthetics}"
