apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [agent]
      interval = "31s"
      flush_interval = "11s"

    [[inputs.http_response]]
      urls = ["https://avi.st"]
      response_status_code = 201
      response_timeout = "6s"
      response_string_match = "cookie.jpg"

    [[inputs.http_response]]
      urls = ["https://pics.avi.st"]
      response_status_code = 201
      response_timeout = "6s"
      response_string_match = "Recent photos"
